services:
  - type: web
    name: taaliqat-bot
    runtime: image
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: PAGE_ACCESS_TOKEN
        sync: false
